{ inputs, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    inputs.noctalia.packages.${stdenv.hostPlatform.system}.default
    gobject-introspection
    wl-clip-persist
    docker-compose
    brightnessctl
    android-tools
    inotify-tools
    sqlitebrowser
    pinentry-all
    wl-clipboard
    pkg-config
    lm_sensors
    playerctl
    cliphist
    hyperhdr
    firefox
    ddcutil
    ghostty
    gnumake
    python3
    clipse
    neovim
    rustup
    socat
    unrar
    meson
    ninja
    cmake
    cairo
    gnupg
    sops
    glib
    wget
    lsof
    gcc
  ];
}
